import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import type { UserPayload } from 'src/types';
import {
  Conversation,
  ConversationDocument,
} from 'src/schemas/inbox/Conversation';
import type { HydratedConversation } from 'src/types';
import PDFDocument from 'pdfkit';

@Injectable()
export class PdfService {
  constructor(
    @InjectModel(Conversation.name)
    private readonly conversationModel: Model<ConversationDocument>,
  ) {}

  async generatePDF(
    chatID: string,
    user: UserPayload,
  ): Promise<{ buffer: Buffer; rolePlayTitle: string }> {
    // Fetch conversation with participants and roleplayAd
    const conversationDoc = await this.conversationModel
      .findById(chatID)
      .populate({
        path: 'participants',
        select: 'username profilePicture',
      })
      .populate({
        path: 'roleplayAd',
        select: '-__v',
      })
      .populate({
        path: 'messages',
        populate: {
          path: 'sender',
          select: 'username profilePicture',
        },
      })
      .lean<HydratedConversation>()
      .exec();

    if (!conversationDoc) {
      throw new Error('Conversation not found');
    }

    // Populate messages with sender info

    const pdfBuffer: Buffer = await new Promise((resolve) => {
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 60, bottom: 60, left: 60, right: 60 },
        bufferPages: true,
        info: {
          Title: `${conversationDoc.roleplayAd.title} Role-Play Transcript`,
        },
      });

      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      /* -----------------------------
       ! HEADER
      ----------------------------- */
      doc
        .fontSize(26)
        .font('Helvetica-Bold')
        .text(`${conversationDoc.roleplayAd.title} Transcript`, {
          align: 'center',
        });
      doc.moveDown(0.5);
      doc
        .strokeColor('#aaaaaa')
        .lineWidth(1)
        .moveTo(doc.page.margins.left, doc.y)
        .lineTo(doc.page.width - doc.page.margins.right, doc.y)
        .stroke();
      doc.moveDown();
      /* -----------------------------
       ! METADATA
      ----------------------------- */
      doc.fontSize(11).fillColor('#555555');

      // Chat ID
      doc
        .font('Helvetica-Bold')
        .text('Chat ID: ', { continued: true })
        .font('Helvetica')
        .text(chatID);

      // Exported for
      if (user) {
        doc
          .font('Helvetica-Bold')
          .text('Exported for: ', { continued: true })
          .font('Helvetica')
          .text(`@${user.username} (User ID: ${user._id})`);
      }

      // Story authors
      doc
        .font('Helvetica-Bold')
        .text('This story was made by: ', { continued: true })
        .font('Helvetica')
        .text(
          conversationDoc.participants
            .map((p) => `@${p.username}`)
            .join(' and '),
        );

      // Date
      doc
        .font('Helvetica-Bold')
        .text('Date: ', { continued: true })
        .font('Helvetica')
        .text(new Date().toLocaleString());

      // Generated by
      doc
        .font('Helvetica-Bold')
        .text('Generated by: ', { continued: true })
        .font('Helvetica')
        .text('TaleWeaver Role-Play App');

      doc.moveDown(1.5);
      /* -----------------------------
       ! STORY CONTEXT
      ----------------------------- */
      doc
        .fontSize(13)
        .font('Helvetica-Bold')
        .fillColor('#000000')
        .text('Story Premise');
      doc.moveDown(0.5);
      const premise = conversationDoc.roleplayAd.premise;
      doc
        .fontSize(11)
        .font('Helvetica-Oblique')
        .fillColor('#333333')
        .text(premise, { lineGap: 4 });
      doc.moveDown(2);
      /* -----------------------------
       ! MESSAGES SECTION
      ----------------------------- */
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .fillColor('#000000')
        .text('Transcript');
      doc.moveDown();

      const allMessages = conversationDoc.messages;

      for (const msg of allMessages) {
        const speaker = msg.sender?.username ?? 'Unknown';

        doc
          .fontSize(11)
          .font('Helvetica-Bold')
          .fillColor('#1a73e8')
          .text(speaker);

        doc
          .fontSize(11)
          .font('Helvetica')
          .fillColor('#000000')
          .text(msg.content, { indent: 12, lineGap: 4 });

        doc.moveDown(1);
      }

      doc
        .moveDown(2)
        .fontSize(10)
        .text(
          '© This document contains a collaborative story created by both role-play participants. ' +
            'It is provided for personal use only and may not be redistributed or used commercially ' +
            'without the consent of all contributors.',
          { align: 'center' },
        );

      doc.end();
    });

    return {
      buffer: pdfBuffer,
      rolePlayTitle: conversationDoc.roleplayAd.title,
    };
  }
}
